#!/bin/bash
clear

function checking_sc() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | awk '{print $4}')

    if echo "$IZIN" | grep -wq "$MYIP"; then
        echo "IZIN DITERIMA ANJING"
    else
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e "\033[44m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "           \e[38;5;196mPERMISSION DENIED !\033[0m"
        echo -e "  \033[0;36mYour VPS IP $MYIP has been banned.\033[0m"
        echo -e "    \033[0;36mBuy access permissions for scripts.\033[0m"
        echo -e "            \033[0;36mContact Admin :\033[0m"
        echo -e "     \033[2;32mWhatsApp\033[0m wa.me/6285888801241"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        exit 1  # Exit with non-zero status to indicate failure
    fi
}

checking_sc
clear


IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
clear



#              LINK JSON TROJAN              #
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"



runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m' # PURPLE SANGAR
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
Xark="\e[0m"


yellow="\033[1;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
Cyan="\e[96;1m"
# . Liner 
function baris_panjang() {
  echo -e "${LO} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${R1}               RISWANVPN     ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[0;36m    Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[0;36m            Script Credit \033[0m"
echo -e "\033[0;36m              RiswanVpn  \033[0m"
baris_panjang
exit 1
}



# // jalankan perintah :  sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

#tr="$(cat ~/log-install.txt | grep -w "Trojan WS " | cut -d: -f2|sed 's/ //g')"
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${user_EXISTS} == '0' ]]; do
Lunatic_Banner
baris_panjang
  echo -e " Just input a number for-"
  echo -e " ${Green}Quota Limit\033[0m"
  echo -e " ${Green}Limit IP\033[0m"
  echo -e " Format GB"
echo ""
  echo -e " \033[33m0\033[0m for Unlimited"
  echo -e " \033[33m0\033[0m for No Limit"
echo ""
baris_panjang
echo ""
read -rp " Username         : " -e user
		user_EXISTS=$(grep -w $user /etc/xray/tro.json | wc -l)

		if [[ ${user_EXISTS} == '1' ]]; then
clear
baris_panjang
			echo ""
			echo -e "${{Red} Sorry Nickname is Ready ! \033[0m "
			echo ""
			read -p "Press any key to back on menu"
			m-tro
		fi
	done


echo
read -p " Limit User (GB)  : " Quota
echo
read -p " Limit User (IP)  : " iplimit
echo
read -p " Expired (days)   : " exp

sleep 1 & loading $!



#.         DATA LIMIT IP TROJAN
#################################################
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/lunatic/limit/trojan/ip
echo -e "$iplimit" > /etc/lunatic/limit/trojan/ip/$user
else
echo > /dev/null
fi


# Data Quota Trojan
if [ -z ${Quota} ]; then
  Quota="0"
fi

QUOTA1=$(echo "${Quota}" | sed 's/[^0-9]*//g')
QUOTA2=$((${QUOTA1} * 1024 * 1024 * 1024))

if [[ ${QUOTA1} != "0" ]]; then
  echo "${QUOTA2}" >/etc/lunatic/limit/trojan/quota/${user}
fi
#################################################

#                   DATA DB TROJAN
#################################################
DATADB=$(cat /etc/trojan/.trojan.db | grep "^#tro#" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
#################################################
uuid=$(cat /proc/sys/kernel/random/uuid)

#         DATA AKUN DI DB
#################################################
# // detail user di data.db
echo "#tro# ${user} ${exp} ${iplimit}" >>/etc/trojan/.trojan.db
#################################################



#.           DATA TANGGAL 
#################################################
tgl=$(date -d "$exp days" +"%d")
bln=$(date -d "$exp days" +"%b")
thn=$(date -d "$exp days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$exp days" +"%Y-%m-%d"`
sed -i '/#LUNATIX-TROJAN#$/a\#tro-user# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/tro.json
sed -i '/#LUNATIX-GRPC#$/a\#tro-user# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/tro.json

#################################################

# // Restart Service
systemctl restart trojs

# // Link Trojan Akun
GRPC="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
TLS="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
WS="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"





#.          DETAIL AKUN USER
#################################################
# // Menyimpan Account Hasil Create
mkdir -p /detail/tro/
cat > /detail/tro/$user.txt <<-END
——————————————————————————————————————— 
           Trojan Account
———————————————————————————————————————
Username         : $user
Quota            : $Quota Gb
Limit ip         : $iplimit Devic
Expiry in        : $exp Day
———————————————————————————————————————
Port No Grpc     : 80-2082-8880
Port Grpc/Tls    : 443-8443-2095
Network          : ws/grpc
Cipers           : aes-128-gcm
patch            : ws/grpc/Wildcard
Uuid Sadowsok    : ${uuid}
———————————————————————————————————————
Link Grpc        : ${trojanlink1}
———————————————————————————————————————
Link no Grpc     : ${trojanlink}
———————————————————————————————————————
Link Ws          : ${trojanlink2}
———————————————————————————————————————
Opem Clash       : https://${domain}:81/trojan-$user.txt
———————————————————————————————————————
END



#.            FORMAT OPENCLASH
#################################################

cat >/var/www/html/trojan-$user.txt <<-END
———————————————————————————————————————

# Format Trojan GO/WS

- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 80
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

# Format Trojan gRPC / Tls

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc
END

# // Get Bot
Send_Notif() {
# // Get Bot
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot$KEY_TELE/sendMessage"
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
TIMES="10"

TEXT="
<code>———————————————————————————————————————</code>
<code>    🟢Trojan successfully created🟢     </code>
<code>———————————————————————————————————————</code>
<code> USERNAME : $user        </code>
<code> LIMIT IP : $iplimit ip  </code>
<code> QUOTA    : $Quota Gb    </code>
<code> ISP VPS  : $ISP         </code>
<code>———————————————————————————————————————</code>
<code> EXPIRED  : $exp Day     </code>
<code>———————————————————————————————————————</code>
<code> DOMAIN   : $domain      </code>
<code>———————————————————————————————————————</code>
<code>       Script     RiswanVpn        </code>
<code>         Thanks Have ordered           </code>
<code>———————————————————————————————————————</code>
"
#.  MEMBERI NOTIF KE TELE SETELAH AKUN DI BUAT
#################################################
curl -s --max-time $TIMES -d "chat_id=${ID_TELE}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
#################################################

}

Send_Notif

systemctl reload xray
syatemctl restart xray
systemctl reload trojs
systemctl restart trojs
systemctl reload nginx
systemctl restart cron





function Details_Account() {
echo -e "\e[97;1m TROJAN  \033[0m"
echo -e ""
echo -e "\e[97;1m Remarks      : ${user} \033[0m" 
echo -e "\e[97;1m Host/IP      : ${domain} \033[0m"
echo -e "\e[97;1m User Quota   : ${Quota} GB \033[0m"
echo -e "\e[97;1m Limit IP     : ${iplimit} IP \033[0m"
echo -e "\e[97;1m Port NTLS    : 443-900 \033[0m" 
echo -e "\e[97;1m port WS      : 80,8880,8080 \033[0m"
echo -e "\e[97;1m Key/pasword  : ${uuid} \033[0m"
echo -e "\e[97;1m ISP          : $ISP \033[0m"
echo -e "\e[97;1m Path         : /trojan-ws \033[0m" 
echo -e "\e[97;1m ServiceName  : trojan-grpc \033[0m"
baris_panjang
}



function Link_Json() {
echo -e "\e[97;1m Link TLS    : ${TLS} \033[0m" 
baris_panjang
echo -e "\e[97;1m Link WS     : ${WS} \033[0m" 
baris_panjang 
echo -e "\e[97;1m Link GRPC   : ${GRPC} \033[0m" 
baris_panjang
echo -e "\e[97;1m OpenClash   : https://${domain}:81/trojan-$user.txt \033[0m" 
}





function Details_Expiry() {
baris_panjang
echo -e " \033[33mExpiry in   : $exp Days \033[0m "
}





Lunatic_Banner
Details_Account
Link_Json
Details_Expiry
Sc_Credit