#!/bin/bash
clear

function checking_sc() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | awk '{print $4}')

    if echo "$IZIN" | grep -wq "$MYIP"; then
        echo "IZIN DITERIMA ANJING"
    else
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e "\033[44m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "           \e[38;5;196mPERMISSION DENIED !\033[0m"
        echo -e "  \033[0;36mYour VPS IP $MYIP has been banned.\033[0m"
        echo -e "    \033[0;36mBuy access permissions for scripts.\033[0m"
        echo -e "            \033[0;36mContact Admin :\033[0m"
        echo -e "     \033[2;32mWhatsApp\033[0m wa.me/6285888801241"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        exit 1  # Exit with non-zero status to indicate failure
    fi
}

checking_sc
clear





# // Get Data Vps
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
clear


# . Liner 
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m' # PURPLE SANGAR
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
Xark="\e[0m"


yellow="\033[1;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
Cyan="\e[96;1m"
# . Liner 
function baris_panjang() {
  echo -e "${LO} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${R1}               RISWANVPN     ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[0;36m    Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[0;36m            Script Credit \033[0m"
echo -e "\033[0;36m              RiswanVpn  \033[0m"
baris_panjang
exit 1
}

# // jalankan perintah sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}









Lunatic_Banner
  echo -e ""
  echo -e " Just input a number for \033[2;32mLimit IP\033[0m"
  echo -e ""
  echo -e " \033[33m0\033[0m for No Limit"
  echo -e ""
baris_panjang
echo ""
read -p " Username      : " user
echo
read -p " Password      : " Pass
echo
read -p " Limit (IP)    : " iplimit
echo
read -p " Expired (day) : " masaaktif

sleep 1 & loading $!



#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/lunatic/limit/ssh/ip/
echo -e "$iplimit" > /etc/lunatic/limit/ssh/ip/$user
else
echo > /dev/null
fi

# // Tugas Cron.d :  autokill 

echo > /etc/cron.d/limitssh-ip
echo "# Autokill" >>/etc/cron.d/limitssh-ip
echo "*/1 * * * *  root /usr/local/sbin/tendang $iplimit" >>/etc/cron.d/limitssh-ip



slkey=$(cat /etc/slowdns/server.pub)
sldomain=$(cat /root/nsdomain)
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $user
expi="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $user &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi

echo "#ssh# ${user} ${Pass} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
clear

mkdir -p /detail/ssh/

cat > /detail/ssh/$user.txt <<-END
——————————————————————————————————————— 
          SSH OVPN Account
———————————————————————————————————————
Username         : $user
Password         : $Pass
limit ip         : $iplimit
Expiry in        : $masaaktif
———————————————————————————————————————
Host             : $domain
Domain slowdns   : $(cat /root/nsdomain)
pubKey           : $slkey
Port Slowdns     : 53-443-22
Port OpenSSH     : 22
Port Dropbear    : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80,8080,2082,2095
Port SSL/TLS     : 443-8443-2095
Port OVPN WS SSL : 443-8443
———————————————————————————————————————
Aktif Selama     : $masaaktif Hari
Dibuat Pada      : $tnggl
Berakhir Pada    : $expe
———————————————————————————————————————
Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
———————————————————————————————————————
Payload WS       : GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
———————————————————————————————————————
Payload Enhnced  : HEAD https://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
———————————————————————————————————————
OVPN Download    : https://$domain:81/
———————————————————————————————————————

END

function Send_Notif(){
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot$KEY_TELE/sendMessage"
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
TIMES="10"
TEXT="
<code>———————————————————————————————————————</code>
<code>   🟢SSHOVPN successfully created🟢     </code>
<code>———————————————————————————————————————</code>
<code> USERNAME : $user        </code>
<code> LIMIT IP : $iplimit ip  </code>
<code> ISP VPS  : $ISP         </code>
<code>———————————————————————————————————————</code>
<code> EXPIRED  : $masaaktif Day     </code>
<code>———————————————————————————————————————</code>
<code> DOMAIN   : $domain      </code>
<code>———————————————————————————————————————</code>
<code>       Script     RiswanVpn        </code>
<code>         Thanks Have ordered           </code>
<code>———————————————————————————————————————</code>
"

#.  MEMBERI NOTIF KE TELE SETELAH AKUN DI BUAT
curl -s --max-time $TIMES -d "chat_id=$ID_TELE&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL

}

Send_Notif











PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf]"





# Details ACcount
function Details_Ssh(){
Lunatic_Banner
baris_panjang
echo -e "  \033[37;1;7mSSH OPENVPN\033[0m"
echo ""
echo -e "\033[3;37m Remark      : $user \033[0m"
echo -e "\033[3;37m Password    : $Pass \033[0m"
echo -e "\033[3;37m Limit Ip    : ${iplimit} Devic \033[0m"
echo -e "\033[3;37m Domain      : $domain \033[0m"
echo -e "\033[3;37m Ns Domain   : $(cat /root/nsdomain) \033[0m"
echo -e "\033[3;37m Pub Key     : $slkey \033[0m"
echo -e "\033[3;37m ISP         : $ISP \033[0m "
echo -e "\033[3;37m OpenSSH     : 443, 80, 22 \033[0m"
echo -e "\033[3;37m Port UDP    : 1-65535 \033[0m"
echo -e "\033[3;37m SSH WS      : 80,8080,8880,2082 \033[0m"
echo -e "\033[3;37m SSL/TLS     : 443 \033[0m"
echo -e "\033[3;37m OVPN UDP    : 2200 \033[0m"
baris_panjang
}



function Copy_Faste(){
echo -e "\033[3;37m Port 80     : $domain:80@$user:$Pass \033[0m"
echo -e "\033[3;37m Port 443    : $domain:443@$user:$Pass \033[0m"
echo -e "\033[3;37m Udp Custom  : $domain:1-65535@$user:$Pass\033[0m"
echo -e "\033[3;37m OpenVpn     : https://$domain:81/ "
echo -e "\033[3;37m Account     : https://$domain:81/ssh-$user.txt "
}



function Details_Payload(){
baris_panjang
echo -e "\033[3;37m Payload WS  : ${PAYLOADWS}\033[0m"
baris_panjang
echo -e "\033[3;37m Payload TLS : ${PAYLOADTLS}\033[0m"
baris_panjang
echo -e "\033[3;37m Payload ENCD: ${PAYLOADHANCED}\033[0m"
baris_panjang
}



function Expiry_Details(){
echo -e "\033[33m Expiry in  : $masaaktif Day \033[0m"
}


Lunatic_Banner
Details_Ssh
Copy_Faste
Details_Payload
Expiry_Details
Sc_Credit