#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
clear
# ==========================================

echo -e "\e[0;35m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\e[92;1m                 DELETE SSH                       \033[0m"
echo -e "\e[0;35m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
users=()
while read expired
do
    AKUN="$(echo $expired | cut -d: -f1)"
    ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
    exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
    status="$(passwd -S $AKUN | awk '{print $2}' )"
    if [[ $ID -ge 1000 ]]; then
        if [[ "$status" = "L" ]]; then
            printf "%-2s %-17s %2s %-17s %2s \n" "${#users[@]}" "$AKUN" "$exp"
        else
            printf "%-2s %-17s %2s %-17s %2s \n" "${#users[@]}" "$AKUN" "$exp"
        fi
        users+=("$AKUN")
    fi
done < /etc/passwd
echo
# Meminta input nomor pengguna yang akan dihapus
read -p " Just Input number : " number

# Mendapatkan username berdasarkan nomor yang dipilih
selected_user=${users[$number]}

if [ -z "$selected_user" ]; then
    echo -e "\e[31;1m number is missing or incorrect\e[0m"
    exit 1
fi

# Menghapus user
if getent passwd $selected_user > /dev/null 2>&1; then
    userdel $selected_user > /dev/null 2>&1
    exp=$(grep -w "^### $selected_user" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^### $selected_user $exp /,/^},{/d" /etc/ssh/.ssh.db
    rm -f /etc/ssh/$selected_user
    rm -f /etc/lunatic/limit/ssh/ip/${selected_user}
    rm -f /etc/lunatic/ssh/ip/${selected_user}
    rm -f /etc/detail/ssh/$selected_user
    rm -f /var/www/html/ssh-$selected_user.txt
    clear
    echo ""
    echo -e "\e[0;36mUser $selected_user berhasil dihapus. \e[0m"
else
    echo -e "\e[31;1mFailure: User \e[32m $selected_user \e[31;1m tidak ditemukan \e[0m"
fi
