#!/bin/bash
#Color
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
RED='\033[0;31m'
green='\e[32m'
PURPLE='\e[35m'
cyan='\e[36m'
LRED='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
blue="\033[0;34m"
WhiteBe="\033[5;37m"
Blue="\033[36m"
clear

echo -e "\e[32mloading...\e[0m"
clear

badvpn1=$(systemctl status vmip | grep running | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

# STATUS SERVICE  BADVPN 1
if [[ $badvpn1 == "running" ]]; then 
   status_udp1="${GREEN}[ ON ]$NC${blue} │$NC"
else
   status_udp1="${RED}[ OF ]\e[0m "
fi

# Status cron
cron_status=$(systemctl is-active cron.service)
if [[ $cron_status == "active" ]]; then
    cron_status="${grenbo}[ ON ]\e[0m"
else
    cron_status="${RED}[ OF ]\e[0m"
fi
clear
echo -e " \e[35;1m┌──────────────────────────────────────────┐\033[0m"
echo -e " \e[97;1m Status cron limit : $cron_status"
echo -e " \e[97;1m Status limit ip   : $cron_status"
echo -e " \e[35;1m└──────────────────────────────────────────┘\033[0m"
echo -e " \e[33;1m┌──────────────────────────────────────────┐\033[0m"
echo -e " \e[97;1m 1. MATIKAN LIMIT IP \e[0m"
echo -e " \e[97;1m 2. NYALAKAN LIMIT IP\e[0m"
echo -e " \e[97;1m 3. SET TIMES LOCK IP\e[0m"
echo -e " \e[97;1m 4. MATIKAN AUTOLOCK \e[0m"
echo -e " \e[97;1m 5. HIDUPKAN AUTOLOK\e[0m"
echo -e " \e[91;1m x. Back To Main Menu \e[0m"
echo -e " \e[35;1m└──────────────────────────────────────────┘\033[0m"

# Fungsi untuk mematikan cron "gon"
stop_cron() {
    # Hapus file cron "gon"
    rm -f "/etc/cron.d/limit-xray"
    rm -f /etc/cron.d/lock-xray

    echo -e "Cron 'gon' berhasil ${RED}dinonaktifkan\e[0m."
}

# Fungsi untuk menyalakan cron "gon"
start_cron() {
    echo "Menyalakan cron 'gon'..."
    systemctl start cron.service
}

# Pilihan fungsi
read -p "Select From Options [ 0 - 5 ] : " menu
case $menu in
    1)
        # Fungsi untuk mematikan limit IP
        clear ;
        cd /etc/systemd/system/
        rm -rf /etc/systemd/system/kill-vme.service
        rm -rf /etc/systemd/system/kill-vle.service
        rm -rf /etc/systemd/system/kill-tro.service
        rm -rf /etc/systemd/system/kill-ssr.service
        systemctl daemon-reload
        reboot
        ;;
    2)
        # Fungsi untuk menyalakan limit IP
        clear ;
        cat >/etc/systemd/system/kill-vme.service << END
        # ... (script untuk menyalakan vmip)
END
        systemctl daemon-reload
        systemctl restart vmip
        systemctl enable vmip

        cat >/etc/systemd/system/kill-vle.service << END
        # ... (script untuk menyalakan vlip)
END
        systemctl daemon-reload
        systemctl restart vlip
        systemctl enable vlip

        cat >/etc/systemd/system/kill-tro.service << END
        # ... (script untuk menyalakan trip)
END
        systemctl daemon-reload
        systemctl restart trip
        systemctl enable trip
        # SERVICE LIMIT QUOTA
        reboot
        cat >/etc/systemd/system/kill-ssr.service << END
        # ... (script untuk menyalakan ssip)
END
        systemctl daemon-reload
        systemctl restart ssip
        systemctl enable ssip
        # SERVICE LIMIT QUOTA
        reboot
        ;;
    3)
        # Fungsi untuk menetapkan jadwal cron kustom
        clear ;
        echo "Masukkan jadwal cron kustom (contoh 1 untuk 1 menit):"
        read -r custom_cron_schedule

        cat >/etc/cron.d/lock-xray <<-END
        SHELL=/bin/sh
        PATH=/luna/run
        $custom_cron_schedule root /luna/run/lock-xray
END
        echo -e "${GREEN}Waktu Banned Akun Telah Di Aktifkan\e[0m\n"
        ;;
    4)
        # Panggil fungsi untuk mematikan cron "gon"
        clear ;
        echo -e "${GREEN}MEMATIKAN CRON GON\e[0m\n"
        stop_cron
        ;;
    5)
    # Panggil fungsi untuk menyalakan cron "gon"
    clear ;
    echo -e "${GREEN}MENYALAKAN CRON GON\e[0m\n"
    start_cron
    ;;
    0)
        clear ;
        menu
        ;;
    *)
        clear ;
        menu
        ;;
esac
