#!/bin/bash
Send_Logging() {
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot${KEY_TELE}/sendMessage"
TIME="10"
TEXT="
<code>====================</code>
<code>MULTI LOGIN XRAY</code>
<code>====================</code>
<code> USERNAME : $user </code>
<code> LIMIT IP : $iplimit</code>
<code> LOGIN IP : $num_accessed_ips </code>
<code>====================</code>
<code> Locked 15 minutes </code>
<code>====================</code>
"

# Mengirim pesan menggunakan curl ke API Telegram
curl -s -X POST $URL -d chat_id=$ID_TELE -d text="$TEXT" -d parse_mode="HTML"
}


# Clear access log
echo -n > /var/log/xray/accessssr.log

# Sleep for 60 seconds to collect access logs
sleep 60

# Ambil daftar pengguna dari direktori batasan IP
declare -a data=($(ls /etc/lunatic/limit/shadowsocks/ip))

for user in "${data[@]}"
do
    # Ambil batasan IP dari file
    iplimit=$(cat /etc/lunatic/limit/shadowsocks/ip/$user)
    
    # Ambil daftar IP yang diakses oleh pengguna dari log akses
    accessed_ips=$(cat /var/log/xray/accessssr.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
    
    # Hitung jumlah IP yang diakses
    num_accessed_ips=$(echo "$accessed_ips" | wc -l)
    
    if [[ $num_accessed_ips -gt $iplimit ]]; then
        # Kunci akun pengguna
        sed -i "/#ssr-user# $user /{n;s/^/#/}" /etc/xray/ssr.json
        systemctl restart ssrjs >> /dev/null 2>&1
        
        # Kirim log
        Send_Logging
        
        # Jadwalkan pembukaan kembali setelah 15 menit
        echo "echo 'sed -i "/#ssr-user# $user /{n;s/^#//}" /etc/xray/ssr.json && systemctl restart xray >> /dev/null 2>&1 && systemctl restart ssrjs >> /dev/null 2>&1' | at now + 15 minutes" | bash
    fi
    
    sleep 0.1
done