#!/bin/bash

runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m' # PURPLE SANGAR
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
Xark="\033[0m"

# . Liner 
function Liner() {
  echo -e "${LO} ——————————————————————————————————— ${Xark} "
}
function Lunatic_Banner() {
clear
Liner
echo -e "${R1}              RISWANVPN      ${Xark} "
Liner
}
function Sc_Credit(){
sleep 1
Liner
echo -e "\033[0;36m    Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[0;36m          Script Credit \033[0m"
echo -e "\033[0;36m            RiswanVpn  \033[0m"
Liner
exit 1
}





# Baca nama dari ssr.json, pisahkan username dan tanggal expired, lalu hilangkan duplikat
users=$(grep -E "^#ssr-user# " "/etc/xray/ssr.json" | sed -E 's/^#ssr-user# ([^ ]+).*/\1/' | awk '!seen[$0]++')



# Show Member List
Lunatic_Banner
Liner
i=1
for user in $users; do
    echo -e "\e[37;1m $i) $user"
    ((i++))
done
Liner

# Count total Account
total_users=$(echo "$users" | wc -l)


# Show total Account
echo -e "\e[92;1m TOTAL : \e[0;36m$total_users Account\e[0m"
Liner
Sc_Credit