#!/bin/bash
function send-logg(){
TEXT="
Notif Quota X-Ray Account
==========================
Username  ：$user
Total Usage：${Usage} / ${checkLimit}
==========================
"
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot${KEY_TELE}/sendMessage"
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
curl -s -X POST $URL -d chat_id=$ID_TELE -d text="$TEXT" -d parse_mode="HTML"
}

  while true; do
  sleep 30
  data=($(cat /etc/xray/vme.json | grep '^#user-vme#' | cut -d ' ' -f 2 | sort | uniq))
  if [[ ! -e /etc/lunatic/limit/vmess/quota ]]; then
  mkdir -p /etc/lunatic/limit/vmess/quota
  fi
  for user in ${data[@]}
  do
  xray api stats --server=127.0.0.1:10085 -name "user>>>${user}>>>traffic>>>downlink" >& /tmp/${user}
  getThis=$(cat /tmp/${user} | awk '{print $1}');
  if [[ ${getThis} != "failed" ]]; then
        downlink=$(xray api stats --server=127.0.0.1:10085 -name "user>>>${user}>>>traffic>>>downlink" | grep -w "value" | awk '{print $2}' | cut -d '"' -f2);
        if [ -e /etc/lunatic/limit/vmess/quota/${user} ]; then
        plus2=$(cat /etc/lunatic/limit/vmess/quota/${user});
        if [[ ${#plus2} -gt 0 ]]; then
        plus3=$(( ${downlink} + ${plus2} ));
        echo "${plus3}" > /etc/lunatic/limit/vmess/quota/"${user}"
        xray api stats --server=127.0.0.1:10085 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        else
        echo "${downlink}" > /etc/lunatic/limit/vmess/quota/"${user}"
        xray api stats --server=127.0.0.1:10085 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
        else
        echo "${downlink}" > /etc/lunatic/limit/vmess/quota/"${user}"
        xray api stats --server=127.0.0.1:10085 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
        else
      echo ""
   fi
done
# Check ur Account
for user in ${data[@]}
  do
    if [ -e /etc/lunatic/limit/vmess/quota/${user} ]; then
      checkLimit=$(cat /etc/lunatic/limit/vmess/quota/${user});
      if [[ ${#checkLimit} -gt 1 ]]; then
      if [ -e /etc/lunatic/limit/vmess/quota/${user} ]; then
      Usage=$(cat /etc/lunatic/limit/vmess/quota/${user});
      if [[ ${Usage} -gt ${checkLimit} ]]; then
      exp=$(grep -w "^#user-vme# $user" "/etc/xray/vme.json" | cut -d ' ' -f 3 | sort | uniq)
      sed -i "/^#user-vme# $user $exp/,/^},{/d" /etc/xray/vme.json
      send-logg
      systemctl restart vmejs >> /dev/null 2>&1
      else
      echo ""
      fi
      else
      echo ""
      fi
      else
      echo ""
      fi
      else
      echo ""
    fi
  done
done
