#!/bin/bash
# LT
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
Xark="\e[0m"

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Cyan="\033[96;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"

runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m' # PURPLE SANGAR
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

# ==========================================

function baris_panjang() {
  echo -e "${LO} ——————————————————————————————————— ${Xark} "
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "\e[92;1m              RISWANVPN      ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\e[0;36m      Terimakasih Telah Menggunakan \033[0m"
echo -e "\e[0;36m             Script Credit \033[0m"
echo -e "\e[0;36m               RiswanVpn  \033[0m"
baris_panjang
exit 1
}


# Getting
MYIP=$(curl -sS ipv4.icanhazip.com);
clear

baris_panjang
echo -e "\e[92;1m              List Member SSH                  "
baris_panjang     
echo -e "\e[92;1mUSERNAME          EXP DATE          STATUS"
baris_panjang

while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "LOCKED"
else
printf "%-17s %2s %-17s %2s \n" "$AKUN" "$exp     " "UNLOCKED"
fi
fi
done < /etc/passwd

baris_panjang
echo -e ""  
read -p " Just input Username : " User

egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "Day Extend : " Days
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
passwd -u $User
usermod -e  $Expiration $User
egrep "^$User" /etc/passwd >/dev/null
echo -e "$Pass\n$Pass\n"|passwd $User &> /dev/null
clear

baris_panjang
echo -e "\e[92;1m       Succesfully Ssh renewed             "
baris_panjang
echo -e ""
echo -e "\e[36;1m Username   : $User"
echo -e "\e[36;1m Days Added : $Days Days"
echo -e "\e[36;1m Expires on : $Expiration_Display"
echo -e ""
baris_panjang
echo
Sc_Credit

else
clear

baris_panjang
echo -e "\e[31;1m        Message For this name                  \e[0m"
baris_panjangxe
echo -e "\e[31;1m   this name is not on the List      "
echo -e ""
baris_panjang
echo
Sc_Credit
fi
