#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }

clear

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Cyan="\033[96;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"

runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m' # PURPLE SANGAR
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'

# . Liner 
function baris_panjang() {
  echo -e "${LO} ——————————————————————————————————— ${Xark} "
}


function Lunatic_Banner() {
clear
baris_panjang
echo -e "${R2}              RISWANVPN      ${Xark} "
baris_panjang
}


function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[0;36m    Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[0;36m           Script Credit \033[0m"
echo -e "\033[0;36m             RiswanVpn  \033[0m"
baris_panjang
exit 1
}


# Baca nama pengguna dari ssr.json, pisahkan username dan tanggal expired, lalu hilangkan duplikat
users=$(grep -E "^#ssr-user# " "/etc/xray/ssr.json" | sed -E 's/^#ssr-user# ([^ ]+).*/\1/' | awk '!seen[$0]++')
# Tampilkan nama pengguna dengan nomor urut
baris_panjang
echo -e "${R1}           RENEW ACCOUNT        \e[0m"
baris_panjang
echo ""

i=1
for user in $users; do
    echo "$i) $user"
    ((i++))
done

echo ""
baris_panjang
echo ""

read -p " Just input Number: " number


# Dapatkan username berdasarkan nomor yang dipilih
selected_user=$(echo "$users" | sed -n "${number}p")
if [ -z "$selected_user" ]; then    
		clear
        Lunatic_Banner
        baris_panjang
		echo ""
		echo -e "${Red} Sorry ${Xark} "
		echo -e ""
		echo -e "${Cyan}"
		echo " Maaf Nama tidak ada "
		echo " Atau Anda salah Memasuk-"
		echo " kan Nama "
		echo -e "${Xark}"
		echo ""
		baris_panjang
Sc_Credit
    exit 1
else
clear
baris_panjang
echo -e "\e[36;1m Input New Data from User\e[32;1m $selected_user\e[0m"
baris_panjang
echo -e ""
echo
read -p " Expired (day)    : " Expiry
echo
read -p " Limit User (GB)  : " Quota
echo
read -p " Limit User (IP)  : " iplimit
echo
echo ""













    exp=$(grep -wE "^#ssr-user# $user" "/etc/xray/ssr.json" | cut -d ' ' -f 3 | sort | uniq)
    mkdir -p /etc/lunatic/limit/shadowsocks/ip
echo ${iplimit} >> /etc/lunatic/limit/shadowsocks/ip/${user}
if [ ! -e /etc/shadowsocks/ ]; then
  mkdir -p /etc/shadowsocks/
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/lunatic/limit/shadowsocks/quota/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $Expiry))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "/#ssr-user# $user/c\#ssr-user# $user $exp4" /etc/xray/ssr.json
    sed -i "/#ssr# $user/c\#ssr# $user $exp4" /etc/shadowsocks/.shadowsocks.db
    systemctl restart xray > /dev/null 2>&1
    systemctl restart ssrjs > /dev/null 2>&1
    clear


function Succesfully_Renew() {
Lunatic_Banner
baris_panjang
    echo -e "${GreenBe} Succesfully ${Xark} "
    echo ""
    echo -e "${R1} "
    echo " Client Name    : $selected_user"
    echo " Expired On     : $exp4 day"
    echo " User Quota     : $Quota gb"
    echo " User Limit IP  : $iplimit dev"
    echo -e "${Xark} "
    echo ""
baris_panjang
Sc_Credit
}


Succesfully_Renew
    fi
