#!/bin/bash
clear
# jalankan loading : sleep 0.9 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

clear

systemctl restart /etc/systemd/system/*.service
# // SSH
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
openvpn_service="$(systemctl show openvpn.service --no-page)"
oovpn=$(echo "${openvpn_service}" | grep 'ActiveState=' | cut -f2 -d=)
dropbear_status=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
fail2ban_service=$(/etc/init.d/fail2ban status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
cron_service=$(systemctl  status cron | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn1=$(systemctl status udp-mini-1 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn2=$(systemctl status udp-mini-2 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn3=$(systemctl status udp-mini-3 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
Iptables=$(systemctl status netfilter-persistent | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
RClocal=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Autorebot=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
UdpSSH=$(systemctl status udp-custom | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
openssh=$( systemctl status ssh | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )

clear

# // Status AutoKiller X-Ray
killvM=$(systemctl status kill-vme | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
killvL=$(systemctl status kill-vle | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
killsS=$(systemctl status kill-ssr | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
killtR=$(systemctl status kill-tro | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear

# // Status AutoLocked X-Ray
LockvM=$(systemctl status lock-vme | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
LockvL=$(systemctl status lock-vle | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
LocksS=$(systemctl status lock-ssr | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
LocktR=$(systemctl status lock-tro | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

# // Status At Now
att=$(systemctl status atd | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)



clear

if [[ $killvM == "running" ]]; then
    sts_vme="\033[92;1m[ON]\e[0m"
else
    sts_vme="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $killvL == "running" ]]; then
    sts_vle="\033[92;1m[ON]\e[0m"
else
    sts_vle="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $killsS == "running" ]]; then
    sts_ssr="\033[92;1m[ON]\e[0m"
else
    sts_ssr="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $killtR == "running" ]]; then
    sts_tro="\033[92;1m[ON]\e[0m"
else
    sts_tro="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $LockvM == "running" ]]; then
    Lock_vme="\033[92;1m[ON]\e[0m"
else
    Lock_vme="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $LockvL == "running" ]]; then
    Lock_vle="\033[92;1m[ON]\e[0m"
else
    Lock_vle="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $LocksS == "running" ]]; then
    Lock_ssr="\033[92;1m[ON]\e[0m"
else
    Lock_ssr="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $LocktR == "running" ]]; then
    Lock_tro="\033[92;1m[ON]\e[0m"
else
    Lock_tro="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $att == "running" ]]; then
    sts_atd="\033[92;1m[ON]\e[0m"
else
    sts_atd="\033[91;1m[OF]\e[0m "
fi











clear

if [[ $openssh == "running" ]]; then
    status_openssh="\033[92;1m[ON]\e[0m"
else
    status_openssh="\033[91;1m[OF]\e[0m "
fi

clear

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1m[ON]\e[0m"
else
    status_ws_epro="\033[91;1m[OF]\e[0m "
fi

clear

# // Trojan Proxy
ss=$( systemctl status xray | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ss == "running" ]]; then
    status_ss="\033[92;1m[ON]\e[0m"
else
    status_ss="\033[91;1m[OF]\e[0m "
fi

clear

# // NGINX
nginx=$( /etc/init.d/nginx status | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $nginx == "running" ]]; then
    status_nginx="\033[92;1m[ON]\e[0m"
else
    status_nginx="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE IPTABLES
if [[ $Iptables == "exited" ]]; then
    status_galo="\033[92;1m[ON]\e[0m"
else
    status_galo="\033[91;1m[OF]\e[0m"
fi

clear

# STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1m[ON]\e[0m"
else
   status_ssh="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE OPENVPN
if [[ $oovpn == "active" ]]; then
  status_openvpn="\033[92;1m[ON]\e[0m"
else
  status_openvpn="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE DROPBEAR
if [[ $dropbear_status == "running" ]]; then 
   status_beruangjatuh="\033[92;1m[ON]\e[0m"
else
   status_beruangjatuh="\033[91;1m[OF]\e[0m \e[0m"
fi

clear

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1m[ON]\e[0m"
else
   status_haproxy="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE  FAIL2BAN 
if [[ $fail2ban_service == "running" ]]; then 
   status_fail2ban="\033[92;1m[ON]\e[0m"
else
   status_fail2ban="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE  CRONS 
if [[ $cron_service == "running" ]]; then 
   status_cron="\033[92;1m[ON]\e[0m"
else
   status_cron="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE  BADVPN 1
if [[ $badvpn1 == "running" ]]; then 
   status_udp1="\033[92;1m[ON]\e[0m"
else
   status_udp1="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE  BADVPN 2
if [[ $badvpn2 == "running" ]]; then 
   status_udp2="\033[92;1m[ON]\e[0m"
else
   status_udp2="\033[91;1m[OF]\e[0m "
fi

clear

# STATUS SERVICE  BADVPN 3
if [[ $badvpn3 == "running" ]]; then 
   status_udp3="\033[92;1m[ON]\e[0m"
else
   status_udp3="\033[91;1m[OF]\e[0m "
fi

clear

if [[ $RClocal == "exited" ]]; then
    status_galoo="\033[92;1m[ON]\e[0m"
else
    status_galoo="\033[91;1m[OF]\e[0m"
fi

clear

if [[ $Autorebot == "exited" ]]; then
    status_galooo="\033[92;1m[ON]\e[0m"
else
    status_galooo="\033[91;1m[OF]\e[0m"
fi

clear

# STATUS SERVICE  SSH UDP 
if [[ $UdpSSH == "running" ]]; then 
   status_udp="\033[92;1m[ON]\e[0m"
else
   status_udp="\033[91;1m[OF]\e[0m "
fi
clear

# // Running Function 

clear
echo ""
echo -e " \033[97;1m│ \033[97;1mSTATUS SSH OPENVPN          $blue=\e[0m $status_ssh"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS UDP CUSTOM           $blue=\e[0m $status_udp"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS OPENVPN              $blue=\e[0m $status_openvpn"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS WS ePRO              $blue=\e[0m $status_ws_epro"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS BadVPN               $blue=\e[0m $status_udp1"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS DROPBEAR             $blue=\e[0m $status_beruangjatuh"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS HAPROXY              $blue=\e[0m $status_haproxy"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS CRON                 $blue=\e[0m $status_cron"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS NGINX                $blue=\e[0m $status_nginx"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS XRAY                 $blue=\e[0m $status_ss"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS KILL SSH             $blue=\e[0m $status_ssh"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS KILL VMESS           $blue=\e[0m $sts_vme"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS KILL VLESS           $blue=\e[0m $sts_vle"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS KILL TRJAN           $blue=\e[0m $sts_tro"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS KILL SDWSK           $blue=\e[0m $sts_ssr"

sleep 0.6 & loading $!

echo -e " \033[97;1m│ \033[97;1mSTATUS KILL TRIALL          $blue=\e[0m $sts_atd"

sleep 0.8 & loading $!


echo -e " \033[0;35m====================================\e[0m"
echo -e " \033[0;36m         ==[ RISWAN VPN ]==      \e[0m"
echo -e " \033[0;35m====================================\e[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
