#!/bin/bash
clear

function checking_sc() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/Garut-SisiBukit/izinsc/main/ip | awk '{print $4}')

    if echo "$IZIN" | grep -wq "$MYIP"; then
        echo "IZIN DITERIMA ANJING"
    else
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e "\033[44m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "           \e[38;5;196mPERMISSION DENIED !\033[0m"
        echo -e "  \033[0;36mYour VPS IP $MYIP has been banned.\033[0m"
        echo -e "    \033[0;36mBuy access permissions for scripts.\033[0m"
        echo -e "            \033[0;36mContact Admin :\033[0m"
        echo -e "     \033[2;32mWhatsApp\033[0m wa.me/6285888801241"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        exit 1  # Exit with non-zero status to indicate failure
    fi
}

checking_sc
clear






#. LINE
function lunatix_liner() {
  echo -e "\033[35;0m ———————————————————————————————————————\033[0m"
}


#. BANNER
function Lunatic_Banner() {
clear
lunatix_liner
echo -e "\033[92;1m                RISWANVPN       \033[0m"
lunatix_liner
}

#. TEXT
function Sc_Credit(){
sleep 1
lunatix_liner
echo -e "\033[0;36m      Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[0;36m             Script Credit \033[0m"
echo -e "\033[0;36m               RiswanVpn  \033[0m"
lunatix_liner
exit 1
}


#. LOADING
# // jalankan perintah sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}


domain=$(cat /etc/xray/domain)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
##########################################
user=LT.VLE-`</dev/urandom tr -dc 0-9 | head -c3`
Quota=1
iplimit=1
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/lunatic/limit/vless/ip/
echo -e "$iplimit" > /etc/lunatic/limit/vless/ip/$user
else
echo > /dev/null
fi




# Generate UUID
uuid=$(cat /proc/sys/kernel/random/uuid)
domain=$(cat /etc/xray/domain)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
##########################################
uuid=$(cat /proc/sys/kernel/random/uuid)
tgl=$(date -d "$minutes days" +"%d")
bln=$(date -d "$minutes days" +"%b")
thn=$(date -d "$minutes days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"



##########################################
clear
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
##########################################



##########################################
Lunatic_Banner
echo ""
read -p " input minutes : " anjing
sleep 0.4 & loading $!

if ! [[ $anjing =~ ^[0-9]+$ ]]; then
    echo "Input harus berupa bilangan bulat positif."
    exit 1
fi

clear
sed -i '/#LUNATIX-VLESS#$/a\#vle-user# '"$user $anjing"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/vle.json
sed -i '/#LUNATIX-GRPC#$/a\#vle-user# '"$user $anjing"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/vle.json




clear

cat >/var/www/html/vless-$user.txt <<-END

# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

---------------------------------------------------
Link Akun Vless 
---------------------------------------------------
Link TLS      : 
${vlesslink1}
---------------------------------------------------
Link none TLS : 
${vlesslink2}
---------------------------------------------------
Link GRPC     : 
${vlesslink3}
---------------------------------------------------


END





Send_Notif() {
# // Get Bot
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot$KEY_TELE/sendMessage"
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
TIMES="10"

TEXT="
<code>—————————————————————————————————————</code>
<code>   🟢Vless successfully created🟢    </code>
<code>—————————————————————————————————————</code>
<code> USERNAME : $user        </code>
<code> LIMIT IP : $iplimit ip  </code>
<code> QUOTA    : $Quota Gb    </code>
<code> ISP VPS  : $ISP         </code>
<code>—————————————————————————————————————</code>
<code> EXPIRED  : $anjing min  </code>
<code>—————————————————————————————————————</code>
<code> DOMAIN   : $domain      </code>
<code>—————————————————————————————————————</code>
<code>      Script     RiswanVpn       </code>
<code>        Thanks Have ordered          </code>
<code>—————————————————————————————————————</code>
"
#.  MEMBERI NOTIF KE TELE SETELAH AKUN DI BUAT
#################################################
curl -s --max-time $TIMES -d "chat_id=${ID_TELE}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
#################################################

}

Send_Notif


systemctl restart vlejs
systemctl restart nginx
systemctl restart cron



if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/lunatic/limit/vless/quota/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^#vle#" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "#vle# ${user} ${anjing} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db





Xark="\e[0m"
yellow="\033[0;33m"



function Details_Account() {
echo -e "${WhiteBe}"
echo -e " TRIALL VLESS "
echo -e ""
echo -e "Remarks     : ${user}"
echo -e "Domain      : ${domain}"
echo -e "User Quota  : ${Quota} GB"
echo -e "port TLS    : 443,900,8443"
echo -e "Location    : $CITY"
echo -e "ISP         : $ISP"
echo -e "Port WS     : 80,8080,8880,2086,2082"
echo -e "Key         : ${uuid}"
echo -e "Encryption  : none"
echo -e "Path TLS    : /vless "
echo -e "ServiceName : vless-grpc"
echo ""
}



function Link_Json() {
lunatix_liner
echo -e " Link TLS   : ${vlesslink1}"
lunatix_liner
echo -e " Link NTLS  : ${vlesslink2}"
lunatix_liner
echo -e " Link GRPC  : ${vlesslink3}"
lunatix_liner
echo -e " OpenClash  : https://${domain}:81/vless-$user.txt"
lunatix_liner
}



function Details_Expiry() {
echo -e "${yellow} Expiry     : $anjing minutes ${Xark} "
echo "userdel -f \"$user\"" | at now + $anjing minutes &> /dev/null
}



Lunatic_Banner
Details_Account
Link_Json
Details_Expiry
Sc_Credit