#!/bin/bash
clear

function checking_sc() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | awk '{print $4}')

    if echo "$IZIN" | grep -wq "$MYIP"; then
        echo "IZIN DITERIMA ANJING"
    else
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e "\033[44m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "           \e[38;5;196mPERMISSION DENIED !\033[0m"
        echo -e "  \033[0;36mYour VPS IP $MYIP has been banned.\033[0m"
        echo -e "    \033[0;36mBuy access permissions for scripts.\033[0m"
        echo -e "            \033[0;36mContact Admin :\033[0m"
        echo -e "     \033[2;32mWhatsApp\033[0m wa.me/6285888801241"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        exit 1  # Exit with non-zero status to indicate failure
    fi
}

checking_sc
clear




# // color validity
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m' # PURPLE SANGAR
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'
Xark="\e[0m"


# . Liner 
function baris_panjang() {
  echo -e "\e[0;36m ———————————————————————————————————————\033[0m"
}

function Lunatic_Banner() {
clear
baris_panjang
echo -e "${R1}                RISWANVPN       \033[0m"
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\e[0;36m     Terimakasih Telah Menggunakan \033[0m"
echo -e "\e[0;36m            Script Credit \033[0m"
echo -e "\e[0;36m              RiswanVpn  \033[0m"
baris_panjang
exit 1
}

# // jalankan perintah sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}






ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
uuid=$(cat /proc/sys/kernel/random/uuid)
user=LT.VME-`</dev/urandom tr -dc 0-9 | head -c3`
Quota=1
iplimit=1




Lunatic_Banner
echo ""
read -p "  Minutes      :    " anjing

if ! [[ $anjing =~ ^[0-9]+$ ]]; then
    echo -e "${ERROR} Just Input Number."
    exit 1
fi
clear

exp_min=$(date -d "+${anjing}" +"%Y-%m-%d %H:%M:%S")
sed -i '/#LUNATIX-VMESS#$/a\#vme-user# '"$user $anjing"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/vme.json
exp_minutes=$(date -d "+${anjing}" +"%Y-%m-%d %H:%M:%S")
sed -i '/#LUNATIX-GRPC#$/a\#vme-user# '"$user $anjing"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/vme.json
clear
asu=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "BUG.COM",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"
systemctl restart vmejs > /dev/null 2>&1
systemctl restart cron > /dev/null 2>&1 


cat >/var/www/html/vmess-$user.txt <<-END


---------------------------------------------------
# Format Vmess WS TLS

- name: Vmess-$user-WS TLS
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess WS Non TLS

- name: Vmess-$user-WS Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess gRPC

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

END


Send_Notif() {
# // Get Bot
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot$KEY_TELE/sendMessage"
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
TIMES="10"

TEXT="
<code>———————————————————————————————————————</code>
<code>    🟢Vmess successfully created🟢     </code>
<code>———————————————————————————————————————</code>
<code> USERNAME : $user        </code>
<code> LIMIT IP : $iplimit ip  </code>
<code> QUOTA    : $Quota Gb    </code>
<code> ISP VPS  : $ISP         </code>
<code>———————————————————————————————————————</code>
<code> EXPIRED  : $anjing min  </code>
<code>———————————————————————————————————————</code>
<code> DOMAIN   : $domain      </code>
<code>———————————————————————————————————————</code>
<code>       Script     RiswanVpn        </code>
<code>         Thanks Have ordered           </code>
<code>———————————————————————————————————————</code>
"
#.  MEMBERI NOTIF KE TELE SETELAH AKUN DI BUAT
#################################################
curl -s --max-time $TIMES -d "chat_id=${ID_TELE}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
#################################################

}

Send_Notif



function Details_Account() {
baris_panjang
echo -e "${WhiteBe}"
echo -e " TRIAL VMESS "
echo -e ""
echo -e " Remarks       : ${user}"
echo -e " Domain        : ${domain}"
echo -e " User Quota    : ${Quota} GB"
echo -e " Limit IP      : ${iplimit}"
echo -e " Port TLS      : 443-900"
echo -e " Port  WS      : 80,8080,8880,2082,2095"
echo -e " Location      : $CITY"
echo -e " ISP           : $ISP"
echo -e " Key / Passwrd : ${uuid}"
echo -e " AlterId       : 0"
echo -e " Security      : auto"
echo -e " Network       : ws"
echo -e " Path          : /vmess"
echo -e " Dynamic Path  : https://bugmu.com/vmess"
echo -e " ServiceName   : vmess-grpc"
echo -e "${Xark}"
}

function Link_Json() {
baris_panjang
echo -e " Link TLS      : ${vmesslink1}"
baris_panjang
echo -e " Link  WS      : ${vmesslink2}"
baris_panjang
echo -e " Link GRPC     : ${vmesslink3}"
baris_panjang
echo -e " OpenClash     : https://${domain}:81/vmess-$user.txt"
baris_panjang

}

function Details_Expiry() {
echo -e "${yellow} Expiry in     : $exp_min Minutes ${Xark} "
echo "userdel -f \"$user\"" | at now + $exp_min minutes &> /dev/null
}


Lunatic_Banner
Details_Account
Link_Json
Details_Expiry
Sc_Credit