#!/bin/bash
clear

function checking_sc() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | awk '{print $4}')

    if echo "$IZIN" | grep -wq "$MYIP"; then
        echo "IZIN DITERIMA ANJING"
    else
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e "\033[44m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "           \e[38;5;196mPERMISSION DENIED !\033[0m"
        echo -e "  \033[0;36mYour VPS IP $MYIP has been banned.\033[0m"
        echo -e "    \033[0;36mBuy access permissions for scripts.\033[0m"
        echo -e "            \033[0;36mContact Admin :\033[0m"
        echo -e "     \033[2;32mWhatsApp\033[0m wa.me/6285888801241"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        exit 1  # Exit with non-zero status to indicate failure
    fi
}

checking_sc
clear



.

ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
clear

#

#. LINER

function lunatix_liner() {
  echo -e "\e[38;5;162m ———————————————————————————————————————\033[0m"
}


#. TEXT

function Sc_Credit(){
sleep 1
lunatix_liner
echo -e "\033[0;36m      Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[0;36m             Script Credit \033[0m"
echo -e "\033[0;36m               RiswanVpn  \033[0m"
lunatix_liner
exit 1
}


#. LOADING
# // jalankan perintah sleep 3 & loading $!
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}


function Lunatic_Banner() {
clear
lunatix_liner
echo -e "\033[92;1m                RISWANVPN       \033[0m"
lunatix_liner
}
###########################
# // GET TRIALL
IP=$(curl -sS ipv4.icanhazip.com)
user=LT.SSH-`</dev/urandom tr -dc X-Z0-9 | head -c4`
Pass=1
iplimit=1
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/lunatic/limit/ssh/ip/
echo -e "$iplimit" > /etc/lunatic/limit/ssh/ip/$user
else
echo > /dev/null
fi


# // Loading



# // Tugas Cron.d :  autokill 

echo > /etc/cron.d/limitssh-ip
echo "# Autokill" >>/etc/cron.d/limit-ssh
echo "*/1 * * * *  root /usr/local/sbin/tendang $iplimit" >>/etc/cron.d/limit-ssh


cat > /luna/run/deltrialssh <<-END
# Menghapus trial ssh setelah waktu habis
if getent passwd $user > /dev/null 2>&1; then
    userdel $user > /dev/null 2>&1
    exp=$(grep -w "^#ssh# $user" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^### $user $exp /,/^},{/d" /etc/ssh/.ssh.db
    rm -f /etc/ssh/$user
    rm -f /etc/lunatic/limit/ssh/ip/${user}
    rm -f /etc/lunatic/ssh/ip/${user}
    rm -f /etc/detail/ssh/$user
    rm -f /var/www/html/ssh-$user.txt
    clear
    echo ""
    echo -e "\e[0;36mUser $user berhasil dihapus. \e[0m"
else
    echo -e "\e[31;1mFailure: User \e[32m $user \e[31;1m tidak ditemukan \e[0m"
fi
END

echo "*/$anjing * * * *  root /luna/run/kill-ssh >>/etc/crontab
echo "*/$anjing * * * *  root /luna/run/kill-ssh >>/etc/cron.d/kill-ssh

############################
clear
slkey=$(cat /etc/slowdns/server.pub)
sldomain=$(cat /root/.nsdomain)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
clear
tgl=$(date -d "$minutes days" +"%d")
bln=$(date -d "$minutes days" +"%b")
thn=$(date -d "$minutes days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$minutes days" +"%Y-%m-%d"` -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$minutes days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $user &> /dev/null




lunatix_liner
clear
Lunatic_Banner
echo -e "\033[35;0m            SET MINUTES    \033[0m         "
lunatix_liner
echo

read -p " Minutes : " anjing




sleep 0.4 & loading $!


Send_Notif() {
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot$KEY_TELE/sendMessage"
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
TIMES="10"

TEXT="
<code>———————————————————————————————————</code>
<code>  🟢SshOvpn successfully created🟢    </code>
<code>———————————————————————————————————</code>
<code> USERNAME : $user        </code>
<code> LIMIT IP : $iplimit ip  </code>
<code> ISP VPS  : $ISP         </code>
<code>———————————————————————————————————</code>
<code> EXPIRED  : $anjing min  </code>
<code>———————————————————————————————————</code>
<code> DOMAIN   : $domain      </code>
<code>———————————————————————————————————</code>
<code>      Script     RiswanVpn       </code>
<code>        Thanks Have ordered          </code>
<code>———————————————————————————————————</code>
"
#.  MEMBERI NOTIF KE TELE SETELAH AKUN DI BUAT
#################################################
curl -s --max-time $TIMES -d "chat_id=${ID_TELE}&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
#################################################

}

Send_Notif





DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi
echo "#ssh# ${user} " >>/etc/ssh/.ssh.db
echo ""
cat > /var/www/html/ssh-$user.txt <<-END
---------------------------------------------------
Format SSH OVPN Account
---------------------------------------------------
Username         : $user
Password         : $Pass
Berakhir Pada    : $minutes Menit
---------------------------------------------------
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
---------------------------------------------------
Payload : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
---------------------------------------------------
OVPN Download : https://$domain:81/
---------------------------------------------------

END
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf] "








Xark='\e[0m'
yellow='\e[33m'
WhiteBe="\e[97;1m"

# Port Account Detail
function Ssh_Details(){
echo -e "${WhiteBe}"
lunatix_liner
echo " SSH OPENVPN "
echo ""
echo " Remark   : ${user}"
echo " pasword  : ${Pass}"
echo " limit ip : ${iplimit}"
echo " Domain   : ${domain}"
echo " Ns Domain: $(cat /root/nsdomain)"
echo " PubKey   : ${slkey}"
echo " Port Udp : 1-65535 "
echo " Port WS  : 80,8880,2082,8080"
echo " Port Tls : 443,8443 "
echo " OpenSSH  : 22,143 "
echo " OVPN Tls : 443 "
echo " Ovpn UdP : 2200 "
echo " Ovpn Tcp : 443 "
lunatix_liner
}






# Payload Detail 
function Payload_Details(){
lunatix_liner
echo -e "${WhiteBe}"
echo " Payload WS    : ${PAYLOADWS}"
lunatix_liner
echo " Payload Tls   : ${PAYLOADTLS}"
lunatix_liner
echo " Payload Hnced : ${PAYLOADHANCED}"
echo -e "${Xark}"
lunatix_liner
}






# Expired Account
function Expiry_Account(){
echo -e "${yellow} Expiry in  : ${anjing} \e[0m"
lunatix_liner
}






Ssh_Details
Payload_Details
Expiry_Account
echo "userdel -f \"$user\"" | at now + $anjing minutes &> /dev/null
Sc_Credit