#!/bin/bash
#
#  |=======================================================================|
#  • Autoscript VPN By LT Project                                          |
#  • LT Project Developer @LunaticTunnel                                   |
#  • Copyright 2015 14 Marc Indonesia [ Saguling ] | [ Bandung barat ]     |
#  • Contack +6285888801241 [ Indonesia ] | [ Whatsapp ]                   |
#  |=======================================================================|
#
clear

function checking_sc() {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | awk '{print $4}')

    if echo "$IZIN" | grep -wq "$MYIP"; then
        echo "IZIN DITERIMA ANJING"
    else
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e "\033[44m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "           \e[38;5;196mPERMISSION DENIED !\033[0m"
        echo -e "  \033[0;36mYour VPS IP $MYIP has been banned.\033[0m"
        echo -e "    \033[0;36mBuy access permissions for scripts.\033[0m"
        echo -e "            \033[0;36mContact Admin :\033[0m"
        echo -e "     \033[2;32mWhatsApp\033[0m wa.me/6285888801241"
        echo -e "\e[38;5;162m────────────────────────────────────────────\033[0m"
        exit 1  # Exit with non-zero status to indicate failure
    fi
}

checking_sc
clear



######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
clear
######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/scriswan/lunaip/main/ip | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
#username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
#certifacate=$(((d1 - d2) / 86400))
clear
######################################



# Count total Account vmess
vme_total=$(grep -E "^#vme-user# " "/etc/xray/vme.json" | sed -E 's/^#vme-user# ([^ ]+).*/\1/' | awk '!seen[$0]++')
VME=$(echo "$vme_total" | wc -l)


# Count total Account vless
vle_total=$(grep -E "^#vle-user# " "/etc/xray/vle.json" | sed -E 's/^#vle-user# ([^ ]+).*/\1/' | awk '!seen[$0]++')
VLE=$(echo "$vle_total" | wc -l)


# Count total Account trojan
tro_total=$(grep -E "^#tro-user# " "/etc/xray/tro.json" | sed -E 's/^#tro-user# ([^ ]+).*/\1/' | awk '!seen[$0]++')
TRO=$(echo "$tro_total" | wc -l)


# Count total Account shadowsocks
ssr_total=$(grep -E "^#ssr-user# " "/etc/xray/ssr.json" | sed -E 's/^#ssr-user# ([^ ]+).*/\1/' | awk '!seen[$0]++')
SSR=$(echo "$ssr_total" | wc -l)


# Count total Account noobzvpns
nob_total=$(grep -E "^#nob# " "/etc/noobzvpns/.noobzvpns" | sed -E 's/^#nob# ([^ ]+).*/\1/' | awk '!seen[$0]++')
NOB=$(echo "$nob_total" | wc -l)


# Count total Account ssh openvpn
ssh_total=$(grep -E "^#ssh# " "/etc/ssh/.ssh.db" | sed -E 's/^#ssh# ([^ ]+).*/\1/' | awk '!seen[$0]++')
SSH=$(echo "$ssh_total" | wc -l)


# // color validity
# // color format 38
runn='\e[38;5;14m' 
acc='\e[38;5;146m'
LO='\e[38;5;162m'
UK='\e[38;5;99m'  # UNGU KOLOT
BK='\e[38;5;196m' # BEREM KOLOT 
R1='\e[38;5;155m' # HEJO SEMU BODAS
R2='\e[38;5;49m'  # HEJO LIME / APEL
BC='\e[38;5;195m' # BODAS CERAH PISAN
HU='\e[38;5;115m' # HEJO SEMU ABU
UB='\e[38;5;147m' # UNGU KABODASAN
KT='\e[38;5;187m' # KONENG TARIGU
Suffix='\e[0m'




function Lunatic_Banner() {
clear
echo -e "\e[38;5;162m  ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[38;5;162m  │\e[0m \033[44;1;97;1m                 RISWANVPN                  \033[0m \e[38;5;162m│\e[0m"
echo -e "\e[38;5;162m  └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m "
}

function Service_System_Operating() {
echo -e "\e[38;5;162m       ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[38;5;162m       │\e[38;5;196m SYSTEM : \e[31m$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m RAM : \e[31m$(free -m | awk 'NR==2 {print $2}') MB   \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m UPTIME : \e[31m$(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m IPVPS : \e[31m$(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m ISP : \e[31m$(cat /etc/xray/isp)    \033[0m "
echo -e "\e[38;5;162m       │\e[38;5;196m DOMAIN : \e[31m$(cat /etc/xray/domain)    \033[0m "
echo -e "\e[38;5;162m       └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m "
echo -e "\e[38;5;162m            ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[38;5;162m            │\e[37;1m ID :\e[92;1m $(cat /usr/bin/user)"
echo -e "\e[38;5;162m            │\e[37;1m Exp.Sc :\e[92;1m $(((d1 - d2) / 86400)).Turn\e[0m"
echo -e "\e[38;5;162m            │\e[37;1m Sc.Version :\e[92;1m 4.4.4 Lt.\e[0m"
echo -e "\e[38;5;162m            └━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m"
}

function List_Account() {
echo -e "\e[38;5;162m             \e[0;35mSSH : $SSH VLESS : $VLE VMESS : $VME \e[0m"
echo -e "\e[38;5;162m             \e[0;36mTRO : $TRO NOOBZ : $NOB SDWSK : $SSR \e[0m"
}

function Acces_Use_Command() {
echo -e "\e[38;5;162m  ┌━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┐\033[0m"
echo -e "\e[33;1m             acces use\033[0m \033[93;1m☞\033[0m \033[92;1mmenu\033[0m \e[33;1m command \033[0m " 
echo -e "\e[38;5;162m  └━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┘\033[0m "
}



Lunatic_Banner
Service_System_Operating
List_Account
Acces_Use_Command
