#!/bin/bash

Send_Logging() {
KEY_TELE=$(sed -n '1p' /root/.notifbot | awk '{print $1}')
ID_TELE=$(sed -n '2p' /root/.notifbot | awk '{print $1}')
URL="https://api.telegram.org/bot${KEY_TELE}/sendMessage"
TIME="10"
TEXT="
<code>=======================</code>
<code>EXPIRED ACCOUNT DELETED</code>
<code>=======================</code>
  <code> SSHOVPN : ✅ </code>
  <code> VMESS   : ✅ </code>
  <code> VLESS   : ✅ </code>
  <code> TROJAN  : ✅ </code>
  <code> SHDWSOK : ✅ </code>
<code>=======================</code>
 <code>BOT LUNATIC TUNNELING</code>
<code>=======================</code>
"
# Mengirim pesan menggunakan curl ke API Telegram
curl -s -X POST $URL -d chat_id=$ID_TELE -d text="$TEXT" -d parse_mode="HTML"
}


##----- Auto Remove Vmess
data=($(cat /etc/xray/vme.json | grep '^#vme-user#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#vme# $user" "/etc/xray/vme.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#vme# $user $exp/,/^},{/d" /etc/xray/vme.json
        sed -i "/^#vme# $user $exp/,/^},{/d" /etc/vmess/.vmess.db
        rm -rf /etc/vmess/$user
        rm -f /etc/lunatic/limit/vmess/ip/$user
	    rm -f /etc/limit/vmess/$user
	    rm -rf /etc/lunatic/limit/vmess/quota/$user
	    rm -f /var/www/html/vmess-$user.txt
	    rm -f /detail/vme/user.txt
    fi
done

systemctl restart xray
systemctl restart vmejs

#----- Auto Remove Vless
data=($(cat /etc/xray/vle.json | grep '^#vle-user#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#vle-user# $user" "/etc/xray/vle.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#vle-user# $user $exp/,/^},{/d" /etc/xray/vle.json
        sed -i "/^#vle# $user $exp/,/^},{/d" /etc/vless/.vless.db
        rm -rf /etc/vless/$user
        rm -f /etc/lunatic/limit/vless/ip/$user
	    rm -f /etc/limit/vless/$user
	    rm -rf /etc/lunatic/limit/vless/quota/$user	    
	    rm -f /var/www/html/vless-$user.txt
	    rm -f /detail/vle/user.txt
    fi
done

systemctl restart xray
systemctl restart vlejs

#----- Auto Remove Trojan
data=($(cat /etc/xray/tro.json | grep '^#tro-user#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#tro-user# $user" "/etc/xray/tro.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#tro-user# $user $exp/,/^},{/d" /etc/xray/tro.json
        sed -i "/^#tro# $user $exp/,/^},{/d" /etc/trojan/.trojan.db
        rm -rf /etc/trojan/$user
        rm -f /etc/lunatic/limit/trojan/ip/$user
	    rm -f /etc/lunatic/limit/trojan/$user
	    rm -f /var/www/html/trojan-$user.txt
	    rm -rf /etc/lunatic/limit/trojan/quota/$user	    
	    rm -f /detail/tro/user.txt
    fi
done
systemctl restart trojs
systemctl restart xray
#----- Auto Remove SS
data=($(cat /etc/xray/ssr.json | grep '^#tro-user##' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#tro-user## $user" "/etc/xray/ssr.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#tro-user## $user $exp/,/^},{/d" /etc/xray/ssr.json
        sed -i "/^#ssr# $user $exp/,/^},{/d" /etc/shadowsocks/.shadowsocks.db
        rm -rf /etc/shadowsocks/$user
        rm -f /etc/lunatic/limit/shadowsocks/ip/$user
 	    rm -rf /etc/lunatic/limit/shadowsocks/quota/$user       
	    rm -f /etc/limit/shadowsocks/$user
	    rm -f /var/www/html/sodosokws-$user.txt
	    rm -f /detail/ssr/user.txt
    fi
done

systemctl restart xray
systemctl restart ssrjs

##------ Auto Remove SSH
hariini=$(date +%d-%m-%Y)
exp=$(grep -w "^#ssh# $user" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sort | uniq)
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d >/tmp/expirelist.txt
totalaccounts=$(cat /tmp/expirelist.txt | wc -l)
for ((i = 1; i <= $totalaccounts; i++)); do
    tuserval=$(head -n $i /tmp/expirelist.txt | tail -n 1)
    username=$(echo $tuserval | cut -f1 -d:)
    userexp=$(echo $tuserval | cut -f2 -d:)
    userexpireinseconds=$(($userexp * 86400))
    tglexp=$(date -d @$userexpireinseconds)
    tgl=$(echo $tglexp | awk -F" " '{print $3}')
    while [ ${#tgl} -lt 2 ]; do
        tgl="0"$tgl
    done
    while [ ${#username} -lt 15 ]; do
        username=$username" "
    done
    bulantahun=$(echo $tglexp | awk -F" " '{print $2,$6}')
    todaystime=$(date +%s)
    if [ $userexpireinseconds -ge $todaystime ]; then
        :
    else
        userdel --force $username
        sed -i "/^#ssh# $user $exp /,/^},{/d" /etc/ssh/.ssh.db
        rm -f /etc/ssh/$user
        rm -f /etc/lunatic/limit/ssh/ip/${user}
        rm -f /var/www/html/ssh-$user.txt
        rm -rf /detail/ssh/$user.txt
    fi
done
systemctl reload ssh
Send_Logging